### ISSUE TITLE
Setup fails eith error: package directory 'dwex/elftools' does not exist

### ISSUE THREAD

**Issue by MattPaulp** [sevaa/dwex#1]
Hi,

I'm assuming i can just clone pyelftools and filebytes to this dir and this will succeed, correct?

P.S This tools seems really cool, looking forward to checking it out

Thanks

**Comment by MattPaulp** [comment]
I'm on Mac btwnd did a pip3 install pyqt5

**Comment by sevaa** [comment]
Oops, forgot about those two. I'm working with somewhat patched versions of both of them, but the vanilla versions might work for you. Just install them both using pip.

Once I publish to pip, I'm going to ship my patched versions alongside. Not there yet, still ironing out the kinks :(

If you're on MacOS, are you going to work with dSYM bundles? That was one of my patches, the version of filebytes that's currently on pip doesn't support those.

**Comment by sevaa** [comment]
UPDATE: I've published the patched dependencies. Please pull the latest and try setup again.

Then use "dwex" to run. The setup creates an executable.

**Comment by MattPaulp** [comment]
I've got bit of a weird setup. I'm working on Mac but pulling in my ELF files from a Linux machine so I won't be using dSYM. Just pulled and it appears to b working well. Thanks!

**Comment by sevaa** [comment]
Update: it's on PyPi now. `pip install dwex` (with `sudo` if necessary).

**Comment by MattPaulp** [comment]
Do you know of any limits to the size of the object files I can use. I'm playing around with a small file for now but I generally use shared object libraries that can be up to a couple gigabytes

**Comment by sevaa** [comment]
I've worked with files up to 20 MB. The performance was decent. It doesn't try to parse and cache the whole file all at once (at least with ELF files). With Mach-O and PE - I have to check.

The are some scenarios that call for parsing the whole file (e. g. the Find command), but if you just click around in the tree, only the elements that you've been looking at are parsed.
