### ISSUE TITLE
Cannot load Playstation 2 ELF.

### ISSUE THREAD

**Issue by Kneesnap** [sevaa/dwex#11]
I get this message upon loading the PS2 ELF I've uploaded below.
"The file contains no DWARF information, or it is in an unsupported format."

My understanding is that there is dwarf debug info in this elf, as other dwarf utilities work on it.

Could it be fixed to support this?
Thanks!

[sles_507.zip](https://github.com/sevaa/dwex/files/5322433/sles_507.zip)

**Comment by sevaa** [comment]
Interesting case. It's an ELF file, but the section names aren't like those on Linux. I'll see if I can parse DWARF out of this...

**Comment by Kneesnap** [comment]
The other program I've used is `dwarf2cpp` https://github.com/pslehisl/dwarf2cpp
I had to modify it slightly since it didn't have handling for unions declared inside of structs, and would exit without saying anything.

However, after making it just leave a comment whenever it encountered that (lazy fix) it exported everything just fine. I was hoping for something that would let me explore the dwarf data more directly though.

**Comment by sevaa** [comment]
Thanks, I'll poke around that tool's sources. That said, dwex was not meant for *exporting* DWARF data. That's what `readelf` and `dwarfdump` are for.

**Comment by Kneesnap** [comment]
Right I'm not looking for exporting. I want something which will let me
explore it. I want to get a better feel for various debug information
formats, as well as confirm I'm utilizing all of the debug data which is
contained in the elf.

**Comment by sevaa** [comment]
Looks like this is DWARF v1, unsupported by pyelftools :( I'm on my own, more or less, but I'll see what I can do.

**Comment by Kneesnap** [comment]
Any luck?

**Comment by sevaa** [comment]
I have to write a DWARF 1 parser from scratch. It's not a one day deal.

**Comment by Kneesnap** [comment]
Gotcha, I misunderstood it as you were going to look for another library.
Ok! Thank you for taking the time to do that.

**Comment by Kneesnap** [comment]
Thanks, I'll check it out. I have the compiler which was used to build
this, I'll see if there's any documentation on that.

**Comment by sevaa** [comment]
Is this still an issue?

**Comment by Kneesnap** [comment]
I assume you're asking if I still need this functionality. I don't hugely
need it, it's not a massive priority. If you don't want to put in the huge
effort it'd take to support DWARFv1 that's totally fine with me. I just
thought it might help me understand the format better if I could use this
tool.

**Comment by sevaa** [comment]
I thought I have provided sufficient support for your purposes in version 0.70. :) I'm really asking if dwex 0.70 opens and displays your PS2 binaries the way you'd like. It works fine (for me) with the provided binary...

**Comment by Kneesnap** [comment]
Oh! I see! I checked master and didn't see any updates! This is wonderful
news, I shall check it out after work. Thank you!

**Comment by sevaa** [comment]
Weird, there was a commit, and a tag, and I've uploaded to PyPI, and Help/Check for updates notices it. What were you looking at?

**Comment by Kneesnap** [comment]
I was checking on my phone, it's quite possible I messed up somehow.

**Comment by Kneesnap** [comment]
I've confirmed it seems to work properly now.
