### ISSUE TITLE
Visualization problem: columns not showns

### ISSUE THREAD

**Issue by martin-paul** [sevaa/dwex#15]
Hi sevaa,

when a DIE is being displayed, which has a very long raw value inside an attribute, the column "Value" is not visible 

see screenshot
![grafik](https://user-images.githubusercontent.com/5786547/101538852-f485f300-399d-11eb-9d97-abc29af1d7ea.png)

probably swapping the column "Raw" and "Value" would resolve this issue

**Comment by martin-paul** [comment]
update: swapping column won't solve the issue - since the long payload is mirrored from "Raw" also to "Value" 

see here:
![grafik](https://user-images.githubusercontent.com/5786547/101540166-e638d680-399f-11eb-98b9-dfaec1d87e9b.png)

**Comment by sevaa** [comment]
Addressed. Grab the latest.

**Comment by martin-paul** [comment]
works like a charm, thanks !

**Comment by sevaa** [comment]
Out of curiosity, what do you turn the low level data display on for? I thought no one's ever going to need that.

**Comment by martin-paul** [comment]
the raw attributes are indeed of no interest. 
The problem was, that i couldn't see the "value" column of the other attributes of a certain DIE, when one of the attributes contained a big payload.

**Comment by sevaa** [comment]
You could uncheck View/Low level, then the raw value won't be displayed at all.

**Comment by martin-paul** [comment]
ah, i wasn't aware of that filter mechanism - thanks :)
