### ISSUE TITLE
Will not install on Apple Silicon

### ISSUE THREAD

**Issue by noppej** [sevaa/dwex#21]
Installation fails with `AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'` on Apple Silicon based hardware.

The solution is to install AND run from a Terminal that is running with the "Open in Rosetta" option.

I suspect that is because `pyqt5` is not supported on Apple Silicon, and if `dwex` upgraded to `pyqt6`, the problem should fix itself.

**Comment by sevaa** [comment]
Makes sense. I'll see what I can do. Chances are I'll maintain a Qt5 version in parallel for some time, just in case.

**Comment by noppej** [comment]
I've been using it today in Rosetta mode and it is still just as useful as it used to be on my older machine.  Thanks for a great app!

**Comment by sevaa** [comment]
Addressed. Versions from 2 are running against PyQt6. I had to drop support for Python 3.5 for that.

**Comment by noppej** [comment]
Thank you :)
