### ISSUE TITLE
Error opening file with DWARF5

### ISSUE THREAD

**Issue by noppej** [sevaa/dwex#23]
Hi,

I've just upgraded to the latest "version 2". When I open files on my Mac (M1 Pro) it fails with an error "Error opening file:"

I've attached the binary, with the hope that you can reproduce.
PS. `dwarfdump` is able to report from the same file.

Tx
[nrf52833.zip](https://github.com/sevaa/dwex/files/7973908/nrf52833.zip)
,

**Comment by sevaa** [comment]
That file contains at least one compile unit with DWARF version 5 (probably the RTL). The `pyelftools` library, which `dwex` is based on, contains DWARFv5 support (somewhat experimental) in the master branch, but not in the released version. The issue in the pyelftools Github is https://github.com/eliben/pyelftools/issues/325 - consider browsing there and ask for a release.

If the maintainers over there won't oblige, I could repackage the latest master of pyelftools with dwex and release like that. But that would leave a bad taste.

**Comment by sevaa** [comment]
Now that I think of it, dwex would do better to show a nicer message. It's not exactly an error. While the pyelftools team gets their act together, I think I'll do that.

**Comment by noppej** [comment]
I've got a number of RUST generated DWARF 5 files if you need someone to help test with the new pyelftools release.

**Comment by sevaa** [comment]
They've obliged, your file opens, I've published, please upgrade dwex and enjoy.

**Comment by noppej** [comment]
Works like a charm. Thanks :)
