### ISSUE TITLE
Opening object files

### ISSUE THREAD

**Issue by koutheir** [sevaa/dwex#28]
Attempting to open an object file (ELF REL) display the message:
```text
Error opening the file:
```
without any further path or reason behind the failure.

Is this tool able to analyze ELF REL files?

**Comment by sevaa** [comment]
Never tried. Can you share the binary, please?

**Comment by koutheir** [comment]
Sure, here it is: [eh-personality.zip](https://github.com/sevaa/dwex/files/8913950/eh-personality.zip).

**Comment by sevaa** [comment]
There was a bug. Stand by for a patch release.

**Comment by sevaa** [comment]
Published, please update and check.

**Comment by koutheir** [comment]
Version 2.14 fixes the issue. Thank you very much!
