### ISSUE TITLE
Error opening the file: 'DW_FORM_line_strp'

### ISSUE THREAD

**Issue by pimvullers** [sevaa/dwex#32]
It looks like there is an issue in processing an ELF file that i'm trying to view in dwex.
After selecting the ELF file from the open file menu I get a dialog box stating:
Error opening the file: 'DW_FORM_line_strp'

Looking at the code, this is some exception thrown when parsing the file, that is only handled at the file_open handler.
1. It would be good if this exception could be handled earlier to translate it to a better error message.
2. It would be nice if the issue that causes the exception gets resolved.

**Comment by sevaa** [comment]
Thanks. Can you share the binary please? If it's sensitive, you don't have to, I have a guess what this might be about.

**Comment by pimvullers** [comment]
FYI, mainly looking at your app as an example how to process DWARF data from ELF files. Due to the relatively tight coupling with PyQt6 I likely cannot reuse the code as is, but potentially might use snippets/ideas (depending on the license, could you please clarify this?).

**Comment by pimvullers** [comment]
[call_main.clang.zip](https://github.com/sevaa/dwex/files/9243566/call_main.clang.zip)

Same source file, now built with clang, new error: _'int' object has no attribute 'decode'_

```
$ clang --version
clang version 14.0.4
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/14/bin
```

I can take pyelftools from master, that's fine.

**Comment by pimvullers** [comment]
Indeed with pyelftools master the file is loaded but the app crashes when I click on a subprogram entry.
Using DWARF-4 seems to work. Will dive into the code and will also look at the differences for pyelftools between 0.28 and master (since I also had some script that uses it, to see if it is affected).

**Comment by sevaa** [comment]
Pyelftools is one PR away from a release :) See https://github.com/eliben/pyelftools/pull/426 and also https://github.com/eliben/pyelftools/issues/421

The changes to pyelftools since 0.28 were pretty profound (I'd know, I was behind some of them), preparing a working monkeypatch would be quite time consuming.

**Comment by pimvullers** [comment]
No need for a patch, I can wait. Subscribed to the release issue.

**Comment by sevaa** [comment]
Published 2.20, your sample binaries open and browse. See if this helps.

**Comment by sevaa** [comment]
Is this still an issue?

**Comment by sevaa** [comment]
@pimvullers
Is this still an issue?
