### ISSUE TITLE
DWARF Symbols in .h Files Do Not Appear in DWARF 4 CCS File

### ISSUE THREAD

**Issue by kierarcher** [sevaa/dwex#37]
Hello,

I reported the following issue on the TI Code Compser Studio forum:

https://e2e.ti.com/support/tools/code-composer-studio-group/ccs/f/code-composer-studio-forum/1220659/dwarf-3-vs-dwarf-4-for-3rd-party-tools

I have no idea if this is an issue with CCS or DWEX but thought you should know.

**Comment by sevaa** [comment]
See if the missing symbols show up in `readelf`, `dwarfdump`, or `llvm-dwarfdump`. If they do, that's a problem with dwex.

**Comment by kierarcher** [comment]
Thank you. I looked for these utils but they are Linux right? I only have Windows, sorry. Is there a Windows utility I can use?

**Comment by kierarcher** [comment]
Thanks for your help. I found readelf under MinGW, sorry, I missed that first time!. The results are inconclusive however because the symbols I'm after do not appear in either the DWARF3 or DWARF4 dump. I used readelf -all, not sure if that's sufficient though?

But I can now supply two ELF files (attached) and refine the problem statement: **Structure members defined in a header file do not appear in DWEX for DWARF4.** See picture. lab_main.h and structure members member1 and member2 are nowhere to be found in the GUI.

My problem is that I don't know if is an issue with the ELF file or not but it would be good if you could confirm DWEX is not at fault here. This means I have more concrete evidence to convince the compiler developers to fix the issue with the ELF file.

My use case is that I'm using the compiler on Windows but the output binary is for a microcontroller.
[driverlib_lp_f28003x_foo.zip](https://github.com/sevaa/dwex/files/11343970/driverlib_lp_f28003x_foo.zip)

**Comment by kierarcher** [comment]
I've got llvm-dwarfdump now. Let me try that.....

**Comment by sevaa** [comment]
[re.zip](https://github.com/sevaa/dwex/files/11344813/re.zip)

Here is the readelf output of the DIE tree of the two binaries. I'll take a look myself too, but you check it in the meantime.

**Comment by kierarcher** [comment]
OK, thank you very much! I'll go back to Texas Instruments armed with this info.
