### ISSUE TITLE
shortcut for going back and forth in click history with left mouse or keyboard shortcut

### ISSUE THREAD

**Issue by martin-paul** [sevaa/dwex#5]
It would be great if it would be possible to jump back to the previous highlighted element/node.
Usecase: for example you follow a ref, afterwards you want to go back to the node which contained the ref.

In addition, going forward in history could also be handy (such that you can jump back and forth again). I would suggest to bind mouse4 + mouse5 to this events.

**Comment by sevaa** [comment]
Already present, menu/Navigate/Back and Forward.

I also had plans to tie that to to Back/Forward mouse buttons, but I don't currently have a mouse with those :)

**Comment by martin-paul** [comment]
i must be blind - thank you ! :)
