### ISSUE TITLE
Incorrect location decode for start address and end address

### ISSUE THREAD

**Issue by KelvinChung2000** [sevaa/dwex#50]
The start and end address displayed is incorrect. 

The correct value on the GUI display should be what is shown at the bottom of the picture. 

<img width="641" alt="image" src="https://github.com/sevaa/dwex/assets/67872121/a4976849-49bf-49de-a307-71d97c249504">

**Comment by sevaa** [comment]
Enable View/Low level, see if it clarifies the picture.

For indexed V5 loclists, readelf does not add the CU's base address to the address offset in the loclist. That's a big in binutils: https://sourceware.org/bugzilla/show_bug.cgi?id=30880

**Comment by sevaa** [comment]
Should be fixed. Please get latest.
