### ISSUE TITLE
Better DW_AT_frame_base information

### ISSUE THREAD

**Issue by KelvinChung2000** [sevaa/dwex#54]
The DW_AT_frame_base then points to a register, an exprloc or a location list. The information will be directly available if is in the form of register or location list. However, when it is an exprloc, which will often point to a single call_frame_cfa, the information is available at the CIE, DW_CFA_def_cfa_register, of the function but not being shown within dwex.

Can we show this information as well? For example, if the DW_AT_frame_base is a single instruction of call_frame_cfa, we will show where the call_frame_cfa is pointed to. Or being more general, attach where call_frame_cfa is pointing to all the time like "call_frame_cfa ->(sp)"

**Comment by sevaa** [comment]
The location of CFA can often change within a single function (any `_alloca` call, for example, will modify the SP value). So the value of `DW_AT_frame_base` can be a single expression `call_frame_cfa`, but what that means can change within the body of the function we are looking at; the call frame info section has its own range->CFA expression table. So it can't be a single `call_frame_cfa -> sp+0x10` line in the general case.

Your need is legitimate, but I'm not sure what's the right UI solution for this. For the time being, in the next version I'll provide a general purpose viewer for the frames section.

The CFA can be pinpointed to a single expression if you have a single value of the address, and I will definitely decode the CFA in the Locals window.

**Comment by KelvinChung2000** [comment]
I think it's good enough as long as the information can be viewed within the same software. But what you mentioned raised some questions and led me to do some digging. 

For DW_AT_frame_base, the result of call_frame_cfa should always be the same if I understand correctly. 

The DWARF5 pdf page 80, lines 19-20 suggest:

> In the context of supporting nested subroutines, the DW_AT_frame_base attribute value obeys the following constraints:
> 1. It computes a value that does not change during the life of the subprogram
> 2. The computed value is unique among instances of the same subroutine.


I guess the `call_frame_cfa ->(sp)` conditions only apply if trying to resolve what `DW_OP_fbreg` points to. Since `DW_OP_fbreg` points to `DW_AT_frame_base`, and if `DW_AT_frame_base` is a single expression of `call_frame_cfa`, then it will always be the same. 

So does this also suggest if `DW_AT_frame_base` is used with `call_frame_cfa`, then the value of  `call_frame_cfa` cannot be modified? So if the `main` `DW_AT_frame_base` using `call_frame_cfa` then does it mean the whole programme did not use any `_alloca` call and did not modify the stack pointer? 

I am now wondering what is the DWARF expression pattern looks like for `_alloca` call.

**Comment by sevaa** [comment]
I'm afraid you've misunderstood the spec. The *value* of the frame base (CFA) doesn't change for the lifetime of the subprogram, since it has to point at the same stack location at all times. The *expression* for it, however, can change. If the expression was, e. g., SP+0x10 in the beginning of the subroutine, and then something happened that decreased the value of SP by 0x10 (e. g. an `_alloca(16)` call :)), the expression for the CFA will become SP+0x20 from that point on.

See page 172 of the same:

>The algorithm to compute CFA changes as you progress through the prologue and 4 epilogue code. (By definition, the CFA value does not change.)

This is encoded by the instructions in the frames section. An CIE/FDE entry contains a variable length array of instructions. Among the instructions, the `DW_CFA_set_loc` and `DW_CFA_advance_locX` move the current code address - that is to say, whatever rules about the CFA follow those, they only apply at and below the current address. Here's a screenshot from an unreleased version of DWEX:

![image](https://github.com/user-attachments/assets/5c0a87a0-094b-46bd-a4ec-40f3555cf012)

**Comment by KelvinChung2000** [comment]
Thanks for the clarification. 

Since the information is relative to the address, a second panel for displaying the general information would probably be best. Would putting the CFA info under a call site make the information navigation easier? Since most of the time, a CFA change is related to a call.

**Comment by sevaa** [comment]
I thought you were after better display of  `DW_AT_frame_base` in `DW_TAG_subroutine` DIEs?

**Comment by KelvinChung2000** [comment]
To me, the frame_base and call site are the same because I look at a call site to track a subroutine. I have not looked at this recently, but I remember the call site does not have information about the call frame.

**Comment by sevaa** [comment]
For the time being, here's what I'm going to do. For a special case of a DWARF expression with but one command `call_frame_cfa`, the details table will be dumping the FDE rules for the current function (all of them). If there is only one rule (that happens in really simple functions), I'll dump the rule inline.

**Comment by sevaa** [comment]
@KelvinChung2000: published an update. See if that works better for you.

**Comment by KelvinChung2000** [comment]
Yes, that works very well for me.

**Comment by sevaa** [comment]
Close the issue, then.
