### ISSUE TITLE
Can not open Golang generate binary

### ISSUE THREAD

**Issue by Zxilly** [sevaa/dwex#57]
With `go version go1.22.4 windows/amd64` and the following code
```go
package main

const aConstant int = 42
const largeConstant uint64 = ^uint64(0)
const minusOne int64 = -1
const stringConstant string = "hello"
var stringVariable string = "world"

func main() {
	println("hello world")
	println(aConstant)
	println(largeConstant)
	println(minusOne)
	println(stringConstant)
	println(stringVariable)
}
```

Using the command `go build -gcflags="all=-N -l" -o b.exe main.go` and open it with dwex results to

![image](https://github.com/user-attachments/assets/349953de-cbbb-4549-a15b-4251c5b99020)

Here's the sample file.

[b.zip](https://github.com/user-attachments/files/16570356/b.zip)

**Comment by sevaa** [comment]
Confirmed. Let me take a closer look.

**Comment by sevaa** [comment]
Published an update, please get it and try now.

**Comment by Zxilly** [comment]
I'm working on other projects these days. Maybe it has been resolved.
