### ISSUE TITLE
Screenshot in README

### ISSUE THREAD

**Issue by langston-barrett** [sevaa/dwex#6]
I'd love to see what this looks like so that I can quickly evaluate whether it might be useful to me without downloading and building it :smile: Thanks!

**Comment by sevaa** [comment]
Provided:

![dwex](https://user-images.githubusercontent.com/5807738/77756810-510ad300-7006-11ea-8d97-b7c109d050b1.png)

That said, there's nothing to build :) Python is an interpreted language.

**Comment by langston-barrett** [comment]
Thanks @sevaa!
