### ISSUE TITLE
Add some example for Find_by_condition option

### ISSUE THREAD

**Issue by skorokhod** [sevaa/dwex#7]

**Comment by sevaa** [comment]
The condition is a Python expression which receives the "die" object to work with. The DIE object comes from the `pyelftools` library. The condition would go something like:

    die.tag == 'DW_TAG_subprogram'

or

   'DW_AT_stmt_list' in die.attributes

The object definition is not mine. I could try to document it, but the definition may change in the future as pyelftools evolves.

**Comment by sevaa** [comment]
No response from the OP, closing.

**Comment by skorokhod** [comment]
I've been lost in time)
Any way,  thak you for your feedback.
Now it's clear
