### ISSUE TITLE
Add the way to filter by string or dwarf tags

### ISSUE THREAD

**Issue by skorokhod** [sevaa/dwex#8]
Is it possible to add some fileter option?
For example, to live just several tags or classes by its names.

**Comment by sevaa** [comment]
Filtering a tree (as opposed to a list) is a tricky proposition. If your filter only leaves certain items in place, that means their parent items should also be shown. Also, it will break the link following logic.

What are you trying to do?

**Comment by skorokhod** [comment]
I need to analyze my data-structures for embedded project.
I'd love to see something like class-view in Visual Studio with real type's sizes, gaps in structs and so on.
The issue is in the number of tag-noise with typedefs, subprograms etc.
May be  some filtering options could simplify this task.
Like "show just listed tags"

**Comment by sevaa** [comment]
A class-view would be way out of scope for this little project. If you want a full blown data structure analysis, you should consider creating your own DWARF reader (e. g. on top of pyelftools).

Would a more capable tag highlighting feature help?

**Comment by sevaa** [comment]
Did highlighting by keyword and by expression. This should do.
