### ISSUE TITLE
LocationParser blocks improper DWARF version

### ISSUE THREAD

**Issue by juansolsona** [sevaa/dwex#9]
Hi there, 

I believe that there is a mistake on the LocationParser. I guess that it restricts to version 4 and above the usage of expression as 
0x00003939:   DW_TAG_variable
                DW_AT_name	("myVariable")
                DW_AT_type	(0x0000294a "const myType")
                DW_AT_external	(true)
                DW_AT_decl_file	("/mySource.c")
                DW_AT_decl_line	(133)
                DW_AT_location	(DW_OP_addr 0x2320)

DWEX only parsers the DW_OP_addr if the DWARF version is >4, but I have found these expressions on files with DWARF v4

I recommend the following change to the code: 

locationlists.py::_attribute_has_loc_expr
Change the condition from
        return ((dwarf_version < 4 and attr.form == 'DW_FORM_block1' and
to 
        return ((dwarf_version <= 4 and attr.form == 'DW_FORM_block1' and

and same change in _attribute_has_loc_list (not tested)

**Comment by sevaa** [comment]
That's an issue in pyelftools, which is not mine. Feel free to file an issue/pull request at https://github.com/eliben/pyelftools
